### ISSUE TITLE
1.0 RC1 Release Checklist

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/systemweb-adapters#210]
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next release/preview
- [x] Identify and validate the build on the `dotnet.systemweb-adapters` pipeline
- [x] Release the build
- [x] Tag the commit
- [x] Draft release notes
- [x] Update samples to use updated package versions
- [x] Publish the docs
- [x] Publish release notes
- [x] Close the [old milestone](https://github.com/dotnet/systemweb-adapters/milestones)
- [x] Announce on social media

**Comment by Tratcher** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2005344&view=artifacts&pathAsName=false&type=publishedArtifacts
Package versions 1.0.0-rc.1.22477.1
