### ISSUE TITLE
1.0 GA Release Checklist

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/systemweb-adapters#239]
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next release/preview (@adityamandaleeka) - https://github.com/dotnet/systemweb-adapters/pull/241
- [x] Identify and validate the build on the `dotnet.systemweb-adapters` pipeline (@twsouthwick)
- [x] Release the build (@adityamandaleeka)
- [x] Tag the commit (@adityamandaleeka)
- [x] Draft release notes (@adityamandaleeka)
- [x] Publish the docs (https://github.com/dotnet/AspNetCore.Docs/pull/27566)
- [x] Publish release notes
- [x] Close the [old milestone](https://github.com/dotnet/systemweb-adapters/milestones)
- [x] 1.0 Announcement blog post (cc @sayedihashimi)
- [x] Announce on social media

**Comment by adityamandaleeka** [comment]
Release notes should include a delta of what's changed from RC1, as well as a link to the announcement blog post.

**Comment by adityamandaleeka** [comment]
PR for updating version to 1.1 Preview 1 https://github.com/dotnet/systemweb-adapters/pull/241

**Comment by adityamandaleeka** [comment]
Docs are up: https://learn.microsoft.com/en-us/aspnet/core/migration/inc/overview?view=aspnetcore-7.0
