### ISSUE TITLE
1.1 GA Release Checklist

### ISSUE THREAD

**Issue by joperezr** [dotnet/systemweb-adapters#301]
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next release/preview (@joperezr) 
- [x] Identify and validate the build on the `dotnet.systemweb-adapters` pipeline (@twsouthwick)
- [x] Release the build (@joperezr)
- [x] Tag the commit (@joperezr)
- [x] Draft release notes (@joperezr)
- [x] Publish the docs
- [x] Publish release notes
- [x] Close the [old milestone](https://github.com/dotnet/systemweb-adapters/milestones)
- [ ] 1.1 Announcement blog post (cc @sayedihashimi)
- [ ] Announce on social media

**Comment by twsouthwick** [comment]
I validated 1.1.0-preview.1.23151.2 and LGTM
